name: Deploy to GitHub Pages

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [15, 16]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm
    - name: Generate the test blog
      run: |
        npm i -g notablog
        notablog generate .
    - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out